apiVersion: v1
kind: Service
metadata:
  name: test-nodeport
  labels:
    app: test-nodeport
spec:
  ports:
  - name: "80"
    nodePort: 32760
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-deployment
  type: NodePort

