apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-lbs
  name: test-lbs
  namespace: default
spec:
  ports:
  - name: "80"
    nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: red-deployment
  type: LoadBalancer

